language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.4"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .
script:
  - ./example/manage.py test categories
