language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.2
install:
  - pip install Django==$DJANGO_VERSION
  - pip install .
  - pip install South
script:
  - ./example/manage.py test categories.tests