language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.2
matrix:
  exclude:
    # Django only started supporting Python 3 in 1.5+
    - python: {"3.1","3.2"}
      env: DJANGO_VERSION=1.4.10
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .
script:
  - ./example/manage.py test categories
